### ISSUE TITLE
Syntax conversion error

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss-selector-not#1]
```css
div:not(.foo, .bar, .baz) {
    color: green;
    font-size: 32px;
}

body >:not(.foo, .bar):not(.baz-inner1) {
  color: red;
}
```

Now convert to:

```css
div:not(.foo), div:not(.bar), div:not(.baz) {
    color: green;
    font-size: 32px;
}

body >:not(.foo):not(.baz-inner1), body >:not(.bar):not(.baz-inner1) {
  color: red;
}
```

**The right syntax should be:**

```css
div:not(.foo):not(.bar):not(.baz) {
    color: green;
    font-size: 32px;
}

body >:not(.foo):not(.bar):not(.baz-inner1) {
  color: red;
}
```

You can test it in WebKit nightly: http://codepen.io/yisi/pen/eNEEaV
