### ISSUE TITLE
README suggests broken uselessness

### ISSUE THREAD

**Issue by 1j01** [postcss/postcss-selector-not#4]
I can see from the tests that it should actually work, but the example output

``` css
p:not(:first-child), p:not(.special) {
  color: red;
}
```

would be equivalent to

``` css
p { color: red; }
```
